import type { Metadata } from "next";
import "./globals.css";
import SideBar from "../component/sideBar/sideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen select-none">
          <div className="flex">
            {/* Sidebar */}
            <div className="hidden lg:block w-[15%] min-w-[25vh] transition-all sticky top-0 min-h-screen shadow-md">
              <SideBar />
            </div>

            {/* Nội dung */}
            <div className="flex flex-[1] flex-col min-h-[100vh] bg-[#e9ecef]">
              {/* <Header back={back} title={title} /> */}
              <div className="flex-[1] bg-[#eff6ff] min-h-[90vh] overflow-y-auto">
                {children}
              </div>
            </div>
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
